name: vibematch
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ffmpeg
  - libsndfile
  - numpy=1.26.*
  - pandas=2.2.*
  - scikit-learn=1.5.*
  - numba=0.59.*
  - llvmlite=0.42.*
  - pip:
      - librosa==0.10.2.post1
      - soundfile==0.12.1
      - joblib==1.4.2
      - boto3==1.35.0
      - python-dotenv==1.0.1
      - streamlit==1.38.0
      - openai>=1.40.0
      - mlflow==2.16.2
